
import fs from 'fs';
import path from 'path';

// --- Configuration ---
const MAPPING_URL = "https://prices.runescape.wiki/api/v1/osrs/mapping";
const OUTPUT_FILE = path.join(__dirname, '../src/data/potions.ts');

interface ItemMapping {
    id: number;
    name: string;
    examine: string;
    members: boolean;
    limit?: number;
    value?: number;
    highalch?: number;
    lowalch?: number;
}

// --- Helpers ---

async function fetchJson<T>(url: string): Promise<T> {
    const res = await fetch(url, {
        headers: { 'User-Agent': 'OSRSTradingTools Scraper' }
    });
    if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.statusText}`);
    return (await res.json()) as T;
}

// --- Main Scraper ---

async function run() {
    try {
        console.log("Fetching Item Mapping...");
        const mapping = await fetchJson<ItemMapping[]>(MAPPING_URL);
        console.log(`Loaded ${mapping.length} items.`);

        // Create Name -> ID lookup
        // Normalizing names to lower case for reliable lookup
        const nameToId = new Map<string, number>();
        const idToItem = new Map<number, ItemMapping>();

        for (const item of mapping) {
            nameToId.set(item.name.toLowerCase(), item.id);
            idToItem.set(item.id, item);
        }

        const foundPotions: Record<string, { dose4: number, dose3: number, dose2: number, dose1: number }> = {};
        let count = 0;

        for (const item of mapping) {
            // Check for ending with "(4)" or " (4)"
            // Regex captures: Group 1 = Base Name, Group 2 = Spacer (empty or space)
            const match = item.name.match(/^(.*?)( ?)\(4\)$/);

            if (match) {
                const baseName = match[1];
                const spacer = match[2]; // "" or " "
                const baseLower = baseName.toLowerCase();

                // Check for existence of other doses using the SAME spacing
                const id3 = nameToId.get(`${baseLower}${spacer}(3)`);
                const id2 = nameToId.get(`${baseLower}${spacer}(2)`);
                const id1 = nameToId.get(`${baseLower}${spacer}(1)`);

                if (id3 && id2 && id1) {
                    // All variants exist
                    foundPotions[baseName] = {
                        dose4: item.id,
                        dose3: id3,
                        dose2: id2,
                        dose1: id1
                    };
                    count++;
                }
            }
        }

        console.log(`\nScraping complete. Found ${count} 4-dose potion sets.`);

        // Generate File Content
        const fileContent = `// Common Potions 4-dose variants
// GENERATED BY SCRAPER - DO NOT EDIT MANUALLY
// Scraped at: ${new Date().toISOString()}

export type PotionDoses = {
    dose4: number;
    dose3: number;
    dose2: number;
    dose1: number;
};

export const POTIONS: Record<string, PotionDoses> = ${JSON.stringify(foundPotions, null, 4)};
`;

        fs.writeFileSync(OUTPUT_FILE, fileContent);
        console.log(`Wrote potion data to ${OUTPUT_FILE}`);

    } catch (err) {
        console.error("Scraper failed:", err);
        process.exit(1);
    }
}

run();
