// Common Potions 4-dose variants
// GENERATED BY SCRAPER - DO NOT EDIT MANUALLY
// Scraped at: 2026-02-02T13:08:41.262Z

export type PotionDoses = {
    dose4: number;
    dose3: number;
    dose2: number;
    dose1: number;
};

export const POTIONS: Record<string, PotionDoses> = {
    "Agility potion": {
        "dose4": 3032,
        "dose3": 3034,
        "dose2": 3036,
        "dose1": 3038
    },
    "Ancient brew": {
        "dose4": 26340,
        "dose3": 26342,
        "dose2": 26344,
        "dose1": 26346
    },
    "Anti-venom": {
        "dose4": 12905,
        "dose3": 12907,
        "dose2": 12909,
        "dose1": 12911
    },
    "Anti-venom+": {
        "dose4": 12913,
        "dose3": 12915,
        "dose2": 12917,
        "dose1": 12919
    },
    "Antidote+": {
        "dose4": 5943,
        "dose3": 5945,
        "dose2": 5947,
        "dose1": 5949
    },
    "Antidote++": {
        "dose4": 5952,
        "dose3": 5954,
        "dose2": 5956,
        "dose1": 5958
    },
    "Antifire potion": {
        "dose4": 2452,
        "dose3": 2454,
        "dose2": 2456,
        "dose1": 2458
    },
    "Antipoison": {
        "dose4": 2446,
        "dose3": 175,
        "dose2": 177,
        "dose1": 179
    },
    "Armadyl brew": {
        "dose4": 31650,
        "dose3": 31653,
        "dose2": 31656,
        "dose1": 31659
    },
    "Attack potion": {
        "dose4": 2428,
        "dose3": 121,
        "dose2": 123,
        "dose1": 125
    },
    "Bastion potion": {
        "dose4": 22461,
        "dose3": 22464,
        "dose2": 22467,
        "dose1": 22470
    },
    "Battlemage potion": {
        "dose4": 22449,
        "dose3": 22452,
        "dose2": 22455,
        "dose1": 22458
    },
    "Blighted overload": {
        "dose4": 29631,
        "dose3": 29634,
        "dose2": 29637,
        "dose1": 29640
    },
    "Combat potion": {
        "dose4": 9739,
        "dose3": 9741,
        "dose2": 9743,
        "dose1": 9745
    },
    "Compost potion": {
        "dose4": 6470,
        "dose3": 6472,
        "dose2": 6474,
        "dose1": 6476
    },
    "Defence potion": {
        "dose4": 2432,
        "dose3": 133,
        "dose2": 135,
        "dose1": 137
    },
    "Divine bastion potion": {
        "dose4": 24635,
        "dose3": 24638,
        "dose2": 24641,
        "dose1": 24644
    },
    "Divine battlemage potion": {
        "dose4": 24623,
        "dose3": 24626,
        "dose2": 24629,
        "dose1": 24632
    },
    "Divine magic potion": {
        "dose4": 23745,
        "dose3": 23748,
        "dose2": 23751,
        "dose1": 23754
    },
    "Divine ranging potion": {
        "dose4": 23733,
        "dose3": 23736,
        "dose2": 23739,
        "dose1": 23742
    },
    "Divine super attack potion": {
        "dose4": 23697,
        "dose3": 23700,
        "dose2": 23703,
        "dose1": 23706
    },
    "Divine super combat potion": {
        "dose4": 23685,
        "dose3": 23688,
        "dose2": 23691,
        "dose1": 23694
    },
    "Divine super defence potion": {
        "dose4": 23721,
        "dose3": 23724,
        "dose2": 23727,
        "dose1": 23730
    },
    "Divine super strength potion": {
        "dose4": 23709,
        "dose3": 23712,
        "dose2": 23715,
        "dose1": 23718
    },
    "Energy potion": {
        "dose4": 3008,
        "dose3": 3010,
        "dose2": 3012,
        "dose1": 3014
    },
    "Extended anti-venom+": {
        "dose4": 29824,
        "dose3": 29827,
        "dose2": 29830,
        "dose1": 29833
    },
    "Extended antifire": {
        "dose4": 11951,
        "dose3": 11953,
        "dose2": 11955,
        "dose1": 11957
    },
    "Extended stamina potion": {
        "dose4": 31638,
        "dose3": 31641,
        "dose2": 31644,
        "dose1": 31647
    },
    "Extended super antifire": {
        "dose4": 22209,
        "dose3": 22212,
        "dose2": 22215,
        "dose1": 22218
    },
    "Extreme energy potion": {
        "dose4": 31614,
        "dose3": 31617,
        "dose2": 31620,
        "dose1": 31623
    },
    "Fishing potion": {
        "dose4": 2438,
        "dose3": 151,
        "dose2": 153,
        "dose1": 155
    },
    "Forgotten brew": {
        "dose4": 27629,
        "dose3": 27632,
        "dose2": 27635,
        "dose1": 27638
    },
    "Goading potion": {
        "dose4": 30137,
        "dose3": 30140,
        "dose2": 30143,
        "dose1": 30146
    },
    "Guthix balance": {
        "dose4": 7660,
        "dose3": 7662,
        "dose2": 7664,
        "dose1": 7666
    },
    "Guthix rest": {
        "dose4": 4417,
        "dose3": 4419,
        "dose2": 4421,
        "dose1": 4423
    },
    "Haemostatic dressing": {
        "dose4": 31590,
        "dose3": 31593,
        "dose2": 31596,
        "dose1": 31599
    },
    "Hunter potion": {
        "dose4": 9998,
        "dose3": 10000,
        "dose2": 10002,
        "dose1": 10004
    },
    "Magic potion": {
        "dose4": 3040,
        "dose3": 3042,
        "dose2": 3044,
        "dose1": 3046
    },
    "Menaphite remedy": {
        "dose4": 27202,
        "dose3": 27205,
        "dose2": 27208,
        "dose1": 27211
    },
    "Olive oil": {
        "dose4": 3422,
        "dose3": 3424,
        "dose2": 3426,
        "dose1": 3428
    },
    "Prayer potion": {
        "dose4": 2434,
        "dose3": 139,
        "dose2": 141,
        "dose1": 143
    },
    "Prayer regeneration potion": {
        "dose4": 30125,
        "dose3": 30128,
        "dose2": 30131,
        "dose1": 30134
    },
    "Ranging potion": {
        "dose4": 2444,
        "dose3": 169,
        "dose2": 171,
        "dose1": 173
    },
    "Relicym's balm": {
        "dose4": 4842,
        "dose3": 4844,
        "dose2": 4846,
        "dose1": 4848
    },
    "Restore potion": {
        "dose4": 2430,
        "dose3": 127,
        "dose2": 129,
        "dose1": 131
    },
    "Sacred oil": {
        "dose4": 3430,
        "dose3": 3432,
        "dose2": 3434,
        "dose1": 3436
    },
    "Sanfew serum": {
        "dose4": 10925,
        "dose3": 10927,
        "dose2": 10929,
        "dose1": 10931
    },
    "Saradomin brew": {
        "dose4": 6685,
        "dose3": 6687,
        "dose2": 6689,
        "dose1": 6691
    },
    "Serum 207": {
        "dose4": 3408,
        "dose3": 3410,
        "dose2": 3412,
        "dose1": 3414
    },
    "Stamina potion": {
        "dose4": 12625,
        "dose3": 12627,
        "dose2": 12629,
        "dose1": 12631
    },
    "Strength potion": {
        "dose4": 113,
        "dose3": 115,
        "dose2": 117,
        "dose1": 119
    },
    "Super antifire potion": {
        "dose4": 21978,
        "dose3": 21981,
        "dose2": 21984,
        "dose1": 21987
    },
    "Super attack": {
        "dose4": 2436,
        "dose3": 145,
        "dose2": 147,
        "dose1": 149
    },
    "Super combat potion": {
        "dose4": 12695,
        "dose3": 12697,
        "dose2": 12699,
        "dose1": 12701
    },
    "Super defence": {
        "dose4": 2442,
        "dose3": 163,
        "dose2": 165,
        "dose1": 167
    },
    "Super energy": {
        "dose4": 3016,
        "dose3": 3018,
        "dose2": 3020,
        "dose1": 3022
    },
    "Super fishing potion": {
        "dose4": 31602,
        "dose3": 31605,
        "dose2": 31608,
        "dose1": 31611
    },
    "Super hunter potion": {
        "dose4": 31626,
        "dose3": 31629,
        "dose2": 31632,
        "dose1": 31635
    },
    "Super restore": {
        "dose4": 3024,
        "dose3": 3026,
        "dose2": 3028,
        "dose1": 3030
    },
    "Super strength": {
        "dose4": 2440,
        "dose3": 157,
        "dose2": 159,
        "dose1": 161
    },
    "Superantipoison": {
        "dose4": 2448,
        "dose3": 181,
        "dose2": 183,
        "dose1": 185
    },
    "Zamorak brew": {
        "dose4": 2450,
        "dose3": 189,
        "dose2": 191,
        "dose1": 193
    }
};
